import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { formatCurrency, formatDate, getStatusColor } from "@/lib/utils";
import { installmentService, expenseService, userService } from "@/service/apiService";
import { useToast } from "@/hooks/use-toast";
import { Calendar, CreditCard, Clock, CheckCircle } from "lucide-react";
import { Parcela, Saida, Usuario } from "../../types";